name: Xiaomi ADB Tools CI

on:
  push:
    branches: [main]
    paths:
      - "xiaomi-adb-tools/**"
      - "!xiaomi-adb-tools/**/*.md"
      - ".github/workflows/xiaomi-adb-tools-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "xiaomi-adb-tools/**"
      - "!xiaomi-adb-tools/**/*.md"
      - ".github/workflows/xiaomi-adb-tools-ci.yml"
  workflow_dispatch:

concurrency:
  group: xiaomi-adb-tools-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: xiaomi-adb-tools
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
        with:
          distribution: temurin
          java-version: "21"

      - uses: gradle/actions/setup-gradle@3f5f9adaf7d9fecd50b5935e54106014257a94e6 # v6.4.0

      - run: ./gradlew platformJars

      - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: XiaomiADBFastbootTools
          path: |
            xiaomi-adb-tools/build/libs/XiaomiADBFastbootTools-*.jar
            xiaomi-adb-tools/build/libs/XiaomiADBFastbootTools-ASSETS.txt
          if-no-files-found: error
          retention-days: 7
